---

- hosts: ios
  gather_facts: no
  connection: local

  tasks:
    - name: show version
      ios_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: result

    - name: fact
      set_fact:
        aaa : "{{ result.stdout[0] | parse_cli_textfsm('./ntc-templates/templates/cisco_ios_show_version.template') }}"
      debug:
        msg: "{{ aaa }}"

  vars:
    cli: 
      host: "{{ inventory_hostname }}" 
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      authorize: true
      auth_pass: "{{ cisco_enable_secret }}"

