---

- hosts: ios
  gather_facts: no
  connection: local

  tasks:
    - name: show version
      ios_command:
        commands:
          - show ip interface 
        provider: "{{ cli }}"
      register: result

    - name: ios_version
      set_fact:
        ios_version : "{{ result.stdout[0] | parse_cli_textfsm('./ntc-templates/templates/cisco_ios_show_ip_interface.template') }}"

#    - name: ios_version_list
#      with_items:
#        "{{ ios_version }}"
#      debug: var=ios_version

    - name: to_csv
      template:
        src: "./tpls.txt"
        dest: "./cisco_ios_show_version_.csv"

    - name: debug
      debug: var=ios_version[0]

  vars:
    cli: 
      host: "{{ inventory_hostname }}" 
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      authorize: true
      auth_pass: "{{ cisco_enable_secret }}"

